export const BUDGET_CATEGORIES: { value: string; label: string }[] = [
  { value: 'fundusz_remontowy',        label: 'Fundusz remontowy' },
  { value: 'fundusz_eksploatacyjny',   label: 'Fundusz eksploatacyjny' },
  { value: 'wynagrodzenie_zarządcy',   label: 'Wynagrodzenie zarządcy' },
  { value: 'koszty_administracji',     label: 'Koszty administracji' },
  { value: 'woda',                     label: 'Woda / kanalizacja' },
  { value: 'śmieci',                   label: 'Odpady / śmieci' },
  { value: 'sprzątanie',               label: 'Sprzątanie' },
  { value: 'opłaty_bankowe',           label: 'Opłaty bankowe' },
  { value: 'przeglądy_budynków',       label: 'Przeglądy budynków' },
  { value: 'remonty',                  label: 'Remonty / naprawy' },
  { value: 'ubezpieczenie',            label: 'Ubezpieczenie' },
  { value: 'energia',                  label: 'Energia / gaz' },
  { value: 'najem',                    label: 'Najem (fundusz eksploatacyjny)' },
  { value: 'podatek_od_nieruchomości', label: 'Podatek od nieruchomości' },
  { value: 'zarząd',                   label: 'Zarządzanie (inne)' },
  { value: 'pozostałe',                label: 'Pozostałe' },
  { value: 'inne',                     label: 'Inne' },
]
